- CMakeLists.txt
- make.bat
- samples/winsvc.app/main.lua
- src/main.c
- src/winsvc.c
- src/winsvc.h
- src/winsvcaux.c
- src/winsvcaux.h
Add support for Windows Services while trying to stay true to the Windows Service Model.
The big differences between this and a Windows Service written in C is that the work done by the service happens in the context of the libUV thread.  StartServiceControlDispatcher is replaced with SpawnServiceControlDispatcher in order for it not to block the libUV thread.  Service control operations are handled by and replied to through lua callbacks for each supported service using libuv's uv_async_send.
> Support for Windows Services

- CMakeLists.txt
Luvit unit tests pass as well. OpenSSL bump is for an include path
> build(freebsd): add freebsd support

- README.md
- src/lua/init.lua
The README says to use a colon to bundle your app with luvit. however the usage from running luvi shows that it should be a semicolon.
> small documentation fix

- CMakeLists.txt
* Causes compile flags /MD to be replace with /MT for Release
* Causes compile flags /MDd to be replace with /MTd for Debug
> Use Static Runtime Library

- Makefile
- README.md
- make.bat
- samples/test.app/main.lua
- src/lua/init.lua
I'm not set on the syntax.
The general idea is that luvi will no longer use environment variables to control it's behavior.  If it detects a zip file appended to itself, it will always run that zip and ignore all arguments (passing them directly to the app).
If there is no zip and it's a bare luvi, then it needs a way for the user to give it the following inputs:
- one or more paths to luvi apps, can default to cwd if none are passed in
- target to build binary
- app-level arguments to be forwarded to main.
Also it would be nice to have things like `-h`, `--help`, `-v`, `--version`, etc.
I'm open to suggestions in the CLI parsing and behavior.
> Refactor luvi to not use environment variables (#80)

- README.md
doc is not synchronized with luvit.io install page. Could be nice to have only one place for doc editing.
> `make test` is needed to obtain luvi binary

- CMakeLists.txt
With commit https://github.com/luvit/luv/commit/c6ce627f404a38044b475b3000139768c36fbb02 the library name for the luajit library is renamed from lua51 to luajit-5.1. Use this name for linking with luajit.
> Change library name from lua51 to luajit-5.1

- cmake/Modules/LuaJITAddExecutable.cmake
Help LuaJIT to find the jit.* modules in build systems like Buildroot where `LUA_PATH` has to be passed through the build environment, else building luvi will fail with:
```
luajit: unknown luaJIT command or jit.* modules not installed
```
Signed-off-by: Jörg Krause <joerg.krause@embedded.rocks>
> Allow to pass LUA_PATH through the environment

- cmake/Modules/LuaJITAddExecutable.cmake
Always passing the `-a` option as a bytecode option has a severe drawback: we need to pass always a target architecture to LuaJIT and cannot use the native build used by LuaJIT if no `-a` is passed.
Fix this by passing the `-a` option conditionally by using the variable `LJ_BYTECODE_OPTS`. This also allows as to pass other bytecode options through the environment.
> LuaJITAddExecutable: pass LJ_BYTECODE_OPTS as bytecode options to LuaJIT

- CMakeLists.txt
- deps/bit.c
- deps/lrexlib.cmake
- deps/lua-openssl.cmake
- deps/lua-zlib.cmake
- src/lenv.c
- src/lminiz.c
- src/lua/luvibundle.lua
- src/luvi.h
- src/main.c
- src/winsvc.c
- src/winsvcaux.c
this is the first version for early review, to fix #140.
second commit resolved most warnings I meet when build on windows using VS2015.
To make this, I can check modifies on other platform (I only tested on Windows)
> pull request for port luvi to Lua 5.3

- deps/miniz.c
Guard some Visual C++ Compiler specific workarounds by using the compiler macro _MSC_VER to silence lot of notes and warnings on a Unix system, like:
```
deps/miniz.c:1313:32: note: in expansion of macro 'MZ_MACRO_END'
} else c = *pIn_buf_cur++; } MZ_MACRO_END
deps/miniz.c:429:30: warning: left-hand operand of comma expression has
no effect [-Wunused-value]
#define MZ_MACRO_END while (0, 0)
```
> deps/miniz: fix some notes and warnings on Unix

- README.md
- The old github url seemed to require prior authorization before cloning
- Steps to configure for `regular` or `tiny` build were missing
> Updating directions for building from source.

- deps/miniz.c
- samples/test.app/main.lua
- src/lminiz.c
This allows users of luvi to use zlib compression without the zlib module, meaning that it is technically no longer necessary.
This has been tested on Debian buster (current testing) on a 64-bit AMD processor, where it appears to work correctly. I expect it to work correctly on all current targets.
I believe I have followed the style of code in my edits, though I will gladly fix any issues that are pointed out.
The API looks something like this, using the example of a deflator:
```lua
local miniz = require("miniz")
local deflator = miniz.new_deflator() -- optionally accepts the compression level to use
local deflated, err, partial = deflator:deflate("input text") -- optionally accepts a flush mode to use
-- if there was an error, deflate returns nil, the error that occured, as well as any …
```
> Add support for zlib compression with miniz (#163)

- README.md
Based on latest version, .stat returns either file or directory:
https://i.imgur.com/6v9KlUz.png
> Fixed stat's types.

- src/main.c
Luvi overrides the vm_acquire callback used by luv to construct the childstate, but it only puts the call to luv_open into package.preload, it doesn't actually load luv. So when luv tried to unmarshal the userdata in the arguments, it looked in the registry for the metatables for the handles, but they weren't set so the userdata got a nil metatable preventing them from being used.
This change makes luvi load luv at lua_State creation instead of just preloading it so that the metatables and type information for luv handles are present when luv thread operations attempt to transfer an async handle across threads.
> Fix passing async handles to threads

- .gitmodules
- Makefile
- appveyor.yml
- deps/lua-openssl.cmake
- deps/openssl.cmake
Migrates to a portable static build of OpenSSL using CMake's ExternalProject_Add. Tested on Windows, Linux, and OSX.
Bumps to Openssl 1.1.0i.
To Test:
```
```
TODO
> Cleanup Static OpenSSL Build

- CMakeLists.txt
The correct way to check if an environment variable is defined is to use `if(DEFINED ENV{})`.
See: https://cmake.org/pipermail/cmake/2011-October/046704.html
> Fix checking if environment variable is defined

- CMakeLists.txt
Running luvi is broken when building with CMake 3.12:
```
[string "return require('init')(...)"]:1: module 'init' not found:
no field package.preload['init']
no file './init.lua'
no file '/usr/share/luajit-2.0.5/init.lua'
no file '/usr/local/share/lua/5.1/init.lua'
no file '/usr/local/share/lua/5.1/init/init.lua'
no file '/usr/share/lua/5.1/init.lua'
no file '/usr/share/lua/5.1/init/init.lua'
no file './init.so'
no file '/usr/local/lib/lua/5.1/init.so'
no file '/usr/lib/lua/5.1/init.so'
no file '/usr/local/lib/lua/5.1/loadall.so'
```
Looking at link.txt for the luvi executable shows that `-rdynamic` is not set anymore in CMake 3.12. This has the effect, that symbols are missing in the `.dynsym` section.
Therefore, set `ENABLE_EXPORTS` to true which sets `-rdynamic` explicitly.
Fixes: #184
> luvi executable needs to export symbols

- deps/lua-openssl.cmake
Fixes build error:
```
deps/lua-openssl/src/sm2.c:6:12: fatal error: openssl/sm2.h: No such file or directory
```
> Update lua-openssl to 0.7.4

- src/luvi_renamed.c
The const was added to __pfnDliFailureHook2 in MSVC 2015 Update 3, so any compilers before that shouldn't define it as const
> Fix __pfnDliFailureHook2 redefinition on MSVC versions < 2015 Update 3

- deps/openssl.cmake
- packaging/Dockerfile.in
- packaging/docker-build.sh
~This is still a WIP.~
We can emulate the build architecture environments with Linux, docker, and qemu-static-$arch binaries.
```
Host machine:
docker run --rm --privileged multiarch/qemu-user-static:register --reset
install qemu-static-binaries
```
Then we can run [multiarch Ubuntu docker images ](https://hub.docker.com/r/multiarch/ubuntu-core/tags/) via:
```
docker run -ti multiarch/ubuntu-core:armhf-bionic bash
```
The general idea is to build luvi within each emulated docker container.
_**I am not sure when I will get back to PR, but if someone is inspired feel free to PR a full solution**_
Resources:
[Cross-Building-and-Running-Multi-Arch-Docker-Images](https://www.ecliptik.com/Cross-Building-and-Running-Multi-Arch-Docker-Images/)
> initial pass at multiplatform builds

- Makefile
This reverts commit 83f187174147d663a443789e7b102a057e8f25ce.
See this comment: https://github.com/luvit/luvi/issues/178#issuecomment-470342437
The standard `get-lit` command also fails for me on my Linux machine (Ubuntu 16.04):
```
./luvi: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./luvi)
./luvi: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1: version `OPENSSL_1_1_1' not found (required by ./luvi)
```
> Revert "Use shared openssl on Linux (#178)"

- appveyor.yml
- deps/openssl.cmake
Closes #197 
Note also that [OpenSSL's INSTALL file](https://github.com/openssl/openssl/blob/master/INSTALL#L269-L273) says the following about the no-asm config setting:
```
no-asm
Do not use assembler code. This should be viewed as
debugging/trouble-shooting option rather than production.
On some platforms a small amount of assembler code may
still be used even with this option.
```
Would it make sense to restructure CMakeLists.txt/make.bat/Makefile so that WithOpenSSLASM=ON is more of a default? Right now `no-asm` is the default and you have to do `make regular-asm` to get what OpenSSL recommends.
> Fix WithOpenSSLASM option being ignored

- appveyor.yml
- make.bat
Only does the deploy phase for tagged commits
Contributes towards #200
---
Tested and confirmed to work. Example:
- Release: https://github.com/squeek502/luvi/releases/tag/v2.9.2-test2
(the bug that caused regular32 not to get included in the release is fixed in this PR)
- Job: https://ci.appveyor.com/project/squeek502/luvi/builds/23387487
- Version Output: `luvi.exe v2.9.2-test2` (i.e. it uses the tag for the version properly)
Note that the `auth_token` used in this PR is one I generated, and I think it'll work for the `luvit/luvi` repo, but maybe it makes more sense for someone else to generate it? See https://www.appveyor.com/docs/deployment/github/#provider-settings for more info about `auth_token`
> Use appveyor to build/release Windows binaries

- .travis.yml
- Makefile
- packaging/holy-build.sh
Uses docker & holy-build-box to build x86_64 and i686 binaries for tagged commits.
Contributes towards #200
---
Tested and confirmed to work. Example:
- Release: https://github.com/squeek502/luvi/releases/tag/v2.9.2-test5
- Job: https://travis-ci.org/squeek502/luvi/builds/512945133
- Version Output: `luvi v2.9.2-test5` (i.e. it uses the tag for the version properly)
> Use travis to build/release Linux binaries 

- Makefile
Makes it a bit more convenient to build with shared openssl, but keeps static openssl as the default
Closes #178
> Add regular-shared make target for shared openssl

- src/snapshot.c
Local variable 'desc' hides a parameter of the same name
> Fix recommendations of lgtm

- .travis.yml
- deps/openssl.cmake
There's no real need to specify UPDATE_COMMAND or UPDATE_DISCONNECTED since as far as I can tell there is no default update step for URL sources, so there's no update that we need to skip.
In older CMake versions, specifying a custom update step with/without UPDATE_DISCONNECTED could cause this error.
CMake bug: https://cmake.org/Bug/view.php?id=15904
CMake docs: https://cmake.org/cmake/help/v3.11/module/ExternalProject.html
Closes #208
> Fix 'openssl-skip-update' make target not found with older CMake versions

- packaging/holy-build.sh
holy-build-box adds -fvisibility=hidden to CFLAGS which causes lua_ and some luv_ symbols to not be globally exported. Now, we simply remove -fvisibility=hidden from CFLAGS before compiling.
This also removes the -g flag from CFLAGS which is something else that holy-build-box sets.
Closes #219
> holy-build: Fix symbol visibility

- samples/test.app/main.lua
- src/lminiz.c
I finally got a chance to use the miniz zlib api (#163 and #165), but I ran into some issues.
1. Byte streams were not fully processed in `inflator:inflate`/`deflator:deflate` when they were larger than the output buffer. This was missed by tests because the they never reached the buffer limit. With inspiration from the [lua-zlib bindings](https://github.com/brimworks/lua-zlib), I added a loop to handle the overflow, and changed the test to parse a larger stream. I also removed the "finish" flush mode from the inflator test, which lua-zlib also seems to omit. We may have to see whether we're properly implementing that.
2. `miniz.compress` was using the wrong stack index for the compression level selection. I factored this out into a helper function and changed the index from 1 to 2 and …
> miniz fixes

- CMakeLists.txt
When performing a build of luvi outside of the source repository or without git, it relies on the presence of a VERSION file. However, it doesn't actually check in the source directory for the VERSION file, meaning it can't find the file, and breaks, putting a git error message in the version number.
This change makes it actually check in the source directory for the VERSION file so it can reliably find it wherever it gets run.
> fix the VERSION file detection in the build script

- main.lua
- samples/test.app/main.lua
- src/luvi_compat.c
Closes #218 
I decided to fix this directly in the C file. Note that `lua_pop` was only called once after requiring the utf8 module. I don't know if this does anything practical, but if it's necessary, I also added a pop for the string module.
Also note that this file seems to mix functions from different Lua versions:
- `luaL_register` is unique to 5.1. It was deprecated in 5.2 in favor of `luaL_setfuncs`.
- `luaL_requiref` was added in 5.2. I guess this is made possible by the presence of the 5.3-compat library.
> Fixes utf8.charpattern in Lua 5.1

- deps/openssl.cmake
- make.bat
`cmake -A` is available since cmake 3.1 (2014).
VS2019 does not allow you to provide the architecture as part of the generator. It must be supplied in the -A switch.
Fixes regression in #239.
*This slipped by the CI because the AppVeyor is still using VS2017.*
> make.bat: use cmake -A to specify architecture 

- appveyor.yml
See #247
Also updated the Travis token, but that's done through environment variable settings so there's no commit necessary there. Hasn't been tested, but hopefully this fixes it.
> Update Github oauth token used for releases

- Makefile
- make.bat
The `--version` of the 2.12.0 release is wrong because of this.
> make: Support lightweight tags when getting luvi version

- src/lminiz.c
luaL_optint removed in lua 5.3 and 5.4
> replace luaL_optint with luaL_optinteger

- cmake/Modules/LuaJITAddExecutable.cmake
Should fix #242
Let me know if this'll work for you @carlocab
> CMake: Make usage of LUA_PATH in LuaJITAddExecutable depend on it being set

- make.bat
It tried to use 2019 by default, and that'll fail if only 2022 is installed. This minor change should have no side effects in other scenarios.
Before:
After:
> Fix CMake builds using Visual Studio 2022

- CMakeLists.txt
These flags are no longer necessary and break the build on ARM64.
See LuaJIT/LuaJIT#649.
Partially resolves #243.
> Remove outdated macOS linker flags

- samples/repl.app/repl.lua
- samples/repl.app/utils.lua
- src/lua/luvibundle.lua
This adds nil or sanity checks for loadstring (replaced by load in Lua 5.2+) and unpack (replaced by table.unpack in 5.2+) and two other variables.
> Adds some nil checks

- CMakeLists.txt
When the project is added as a cmake subproject the VERSION file is under CMAKE_CURRENT_SOURCE_DIR and not CMAKE_SOURCE_DIR.
> Support VERSION check when luvi added with add_subdirectory()

- src/lua/luvibundle.lua
Bug introduced in #276:
```lua
if compile and isLua and name:lower() ~= 'package.lua' then
local fn, err = load(ctx, child)
if not fn and not options.force then
error(err)
else
ctx = string.dump(fn, options.strip)
end
end
```
When `load` fails, `fn` is `nil`. If `options.force` is `true`, `string.dump` is called with `nil` and also fails.
This change removes the attempt to call `string.dump` with `nil`. Obviously, the resulting code will not be compiled or stripped in the bundle.
> Fixes build forcing during Lua load error

- Makefile
nmake doesn't support `+=`, instead use old string substitution
> fix minor typo in new Makefile

- .github/workflows/ci.yml
- CMakeLists.txt
- cmake/Modules/FindLibuv.cmake
- cmake/Modules/FindLuaJIT.cmake
- cmake/Modules/FindLuv.cmake
- cmake/Modules/FindPCRE2.cmake
- deps/pcre2.cmake
also adds a CI check for building with all shared libraries to ensure they don't regress
Most of these regressions were introduced in #285 as a result of not being covered by CI
Primarily focused on fixing #280
> various fixes for building with shared libraries

- src/lminiz.c
Using the default value for the first parameter of `lminiz.adler32` will output invalid checksum due to improper defaults.
For example:
```lua
local miniz = requrie("miniz")
miniz.adler32(nil, "luvit") --> 110625332
```
Which is wrong, it should instead be `110953013` (`0x069D0235`).
For reference take the output of an online calculatore like [this one](https://miniwebtool.com/adler32-checksum-calculator/) or even the [Wikipedia example](https://en.wikipedia.org/wiki/Adler-32#Example).
An Adler32 checksum is 32-bit number made of two 16-bit groups A and B, group A should initiate with `1` and group B should initiate with `0`. Currently by default group A will default to `0` instead of `1`.
@zhaozg Is this right?
> fix: adler32's first 16-bit should default to 1 not 0

- CMakeLists.txt
- src/luvi.h
- src/main.c
A portion of Luvi code is embedded into the binary as bytecode. This poses an issue in builds with shared libluv (and therefore shared luajit) where the version of Lua(JIT) used to compile Luvi may be different from the version present on the target machine.
Both LuaJIT and PUC Lua 5.2+ provide mechanisms to emit an error when this occurs. In PUC Lua this is done via `luaL_checkversion(L)` which throws a Lua error when it fails. We call this as soon as we create a new state to ensure that the error is fatal.
In LuaJIT this is done via an exported symbol `LUAJIT_VERSION_SYM` that matches the version of LuaJIT during compilation. The dynamic loader will fail if this symbol cannot be found in the LuaJIT dynamic library.
These checks happen on a best effort basis: some distributions (like …
> enforce lua version compatibility

- Makefile
- deps/openssl.cmake
Updates to the latest stable openssl, this series
has support past the end of the current LTS, and
we have no reason to stay on 3.0.
Now autodetects an existing openssl installation
and uses it for `--openssldir`.
Removes existing `no-*` options that have been
default for a long time.
Adds `no-pinshared` because we're using a static
openssl and don't need it to pin the executable.
Replaces `no-unit-test` (a default) with `no-tests`
to ensure tests are not compiled.
Removes `no-stdio` because `FILE` may be useful,
and it allows generating the openssl `apps/*` for
debugging.
Adds `no-makedepend` because we're running this
once and it roughly halves the number of cc calls.
Which matters quite a bit on Windows.
-----
Additionally passes `-Wno-dev` to cmake, it gets rid of the cmake policy …
> build: audit openssl configure, update to openssl 3.4.0

- .github/workflows/ci.yml
- CMakeLists.txt
- deps/openssl.cmake
> fix: add `no-module` to openssl static build
